// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scheduler.proto

package mesosproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Possible event types, followed by message definitions if
// applicable.
type Event_Type int32

const (
	// This must be the first enum value in this list, to
	// ensure that if 'type' is not set, the default value
	// is UNKNOWN. This enables enum values to be added
	// in a backwards-compatible way. See: MESOS-4997.
	Event_UNKNOWN                 Event_Type = 0
	Event_SUBSCRIBED              Event_Type = 1
	Event_OFFERS                  Event_Type = 2
	Event_INVERSE_OFFERS          Event_Type = 9
	Event_RESCIND                 Event_Type = 3
	Event_RESCIND_INVERSE_OFFER   Event_Type = 10
	Event_UPDATE                  Event_Type = 4
	Event_UPDATE_OPERATION_STATUS Event_Type = 11
	Event_MESSAGE                 Event_Type = 5
	Event_FAILURE                 Event_Type = 6
	Event_ERROR                   Event_Type = 7
	// Periodic message sent by the Mesos master according to
	// 'Subscribed.heartbeat_interval_seconds'. If the scheduler does
	// not receive any events (including heartbeats) for an extended
	// period of time (e.g., 5 x heartbeat_interval_seconds), there is
	// likely a network partition. In such a case the scheduler should
	// close the existing subscription connection and resubscribe
	// using a backoff strategy.
	Event_HEARTBEAT Event_Type = 8
)

var Event_Type_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "SUBSCRIBED",
	2:  "OFFERS",
	9:  "INVERSE_OFFERS",
	3:  "RESCIND",
	10: "RESCIND_INVERSE_OFFER",
	4:  "UPDATE",
	11: "UPDATE_OPERATION_STATUS",
	5:  "MESSAGE",
	6:  "FAILURE",
	7:  "ERROR",
	8:  "HEARTBEAT",
}

var Event_Type_value = map[string]int32{
	"UNKNOWN":                 0,
	"SUBSCRIBED":              1,
	"OFFERS":                  2,
	"INVERSE_OFFERS":          9,
	"RESCIND":                 3,
	"RESCIND_INVERSE_OFFER":   10,
	"UPDATE":                  4,
	"UPDATE_OPERATION_STATUS": 11,
	"MESSAGE":                 5,
	"FAILURE":                 6,
	"ERROR":                   7,
	"HEARTBEAT":               8,
}

func (x Event_Type) Enum() *Event_Type {
	p := new(Event_Type)
	*p = x
	return p
}

func (x Event_Type) String() string {
	return proto.EnumName(Event_Type_name, int32(x))
}

func (x *Event_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Event_Type_value, data, "Event_Type")
	if err != nil {
		return err
	}
	*x = Event_Type(value)
	return nil
}

func (Event_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{0, 0}
}

// Each of the responses of type `FOO` corresponds to `Foo` message below.
type Response_Type int32

const (
	Response_UNKNOWN Response_Type = 0
	// DEPRECATED.
	//
	// See 'ReconcileOperations' below.
	Response_RECONCILE_OPERATIONS Response_Type = 1 // Deprecated: Do not use.
)

var Response_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "RECONCILE_OPERATIONS",
}

var Response_Type_value = map[string]int32{
	"UNKNOWN":              0,
	"RECONCILE_OPERATIONS": 1,
}

func (x Response_Type) Enum() *Response_Type {
	p := new(Response_Type)
	*p = x
	return p
}

func (x Response_Type) String() string {
	return proto.EnumName(Response_Type_name, int32(x))
}

func (x *Response_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Response_Type_value, data, "Response_Type")
	if err != nil {
		return err
	}
	*x = Response_Type(value)
	return nil
}

func (Response_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{1, 0}
}

// Possible call types, followed by message definitions if
// applicable.
type Call_Type int32

const (
	// See comments above on `Event::Type` for more details on this enum value.
	Call_UNKNOWN                      Call_Type = 0
	Call_SUBSCRIBE                    Call_Type = 1
	Call_TEARDOWN                     Call_Type = 2
	Call_ACCEPT                       Call_Type = 3
	Call_DECLINE                      Call_Type = 4
	Call_ACCEPT_INVERSE_OFFERS        Call_Type = 13
	Call_DECLINE_INVERSE_OFFERS       Call_Type = 14
	Call_REVIVE                       Call_Type = 5
	Call_KILL                         Call_Type = 6
	Call_SHUTDOWN                     Call_Type = 7
	Call_ACKNOWLEDGE                  Call_Type = 8
	Call_ACKNOWLEDGE_OPERATION_STATUS Call_Type = 15
	Call_RECONCILE                    Call_Type = 9
	Call_RECONCILE_OPERATIONS         Call_Type = 16
	Call_MESSAGE                      Call_Type = 10
	Call_REQUEST                      Call_Type = 11
	Call_SUPPRESS                     Call_Type = 12
)

var Call_Type_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "SUBSCRIBE",
	2:  "TEARDOWN",
	3:  "ACCEPT",
	4:  "DECLINE",
	13: "ACCEPT_INVERSE_OFFERS",
	14: "DECLINE_INVERSE_OFFERS",
	5:  "REVIVE",
	6:  "KILL",
	7:  "SHUTDOWN",
	8:  "ACKNOWLEDGE",
	15: "ACKNOWLEDGE_OPERATION_STATUS",
	9:  "RECONCILE",
	16: "RECONCILE_OPERATIONS",
	10: "MESSAGE",
	11: "REQUEST",
	12: "SUPPRESS",
}

var Call_Type_value = map[string]int32{
	"UNKNOWN":                      0,
	"SUBSCRIBE":                    1,
	"TEARDOWN":                     2,
	"ACCEPT":                       3,
	"DECLINE":                      4,
	"ACCEPT_INVERSE_OFFERS":        13,
	"DECLINE_INVERSE_OFFERS":       14,
	"REVIVE":                       5,
	"KILL":                         6,
	"SHUTDOWN":                     7,
	"ACKNOWLEDGE":                  8,
	"ACKNOWLEDGE_OPERATION_STATUS": 15,
	"RECONCILE":                    9,
	"RECONCILE_OPERATIONS":         16,
	"MESSAGE":                      10,
	"REQUEST":                      11,
	"SUPPRESS":                     12,
}

func (x Call_Type) Enum() *Call_Type {
	p := new(Call_Type)
	*p = x
	return p
}

func (x Call_Type) String() string {
	return proto.EnumName(Call_Type_name, int32(x))
}

func (x *Call_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Call_Type_value, data, "Call_Type")
	if err != nil {
		return err
	}
	*x = Call_Type(value)
	return nil
}

func (Call_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{2, 0}
}

//*
// Scheduler event API.
//
// An event is described using the standard protocol buffer "union"
// trick, see:
// https://developers.google.com/protocol-buffers/docs/techniques#union.
type Event struct {
	// Type of the event, indicates which optional field below should be
	// present if that type has a nested message definition.
	// Enum fields should be optional, see: MESOS-4997.
	Type                  *Event_Type                  `protobuf:"varint,1,opt,name=type,enum=mesos.v1.Event_Type" json:"type,omitempty"`
	Subscribed            *Event_Subscribed            `protobuf:"bytes,2,opt,name=subscribed" json:"subscribed,omitempty"`
	Offers                *Event_Offers                `protobuf:"bytes,3,opt,name=offers" json:"offers,omitempty"`
	InverseOffers         *Event_InverseOffers         `protobuf:"bytes,9,opt,name=inverse_offers,json=inverseOffers" json:"inverse_offers,omitempty"`
	Rescind               *Event_Rescind               `protobuf:"bytes,4,opt,name=rescind" json:"rescind,omitempty"`
	RescindInverseOffer   *Event_RescindInverseOffer   `protobuf:"bytes,10,opt,name=rescind_inverse_offer,json=rescindInverseOffer" json:"rescind_inverse_offer,omitempty"`
	Update                *Event_Update                `protobuf:"bytes,5,opt,name=update" json:"update,omitempty"`
	UpdateOperationStatus *Event_UpdateOperationStatus `protobuf:"bytes,11,opt,name=update_operation_status,json=updateOperationStatus" json:"update_operation_status,omitempty"`
	Message               *Event_Message               `protobuf:"bytes,6,opt,name=message" json:"message,omitempty"`
	Failure               *Event_Failure               `protobuf:"bytes,7,opt,name=failure" json:"failure,omitempty"`
	Error                 *Event_Error                 `protobuf:"bytes,8,opt,name=error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                     `json:"-"`
	XXX_unrecognized      []byte                       `json:"-"`
	XXX_sizecache         int32                        `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetType() Event_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Event_UNKNOWN
}

func (m *Event) GetSubscribed() *Event_Subscribed {
	if m != nil {
		return m.Subscribed
	}
	return nil
}

func (m *Event) GetOffers() *Event_Offers {
	if m != nil {
		return m.Offers
	}
	return nil
}

func (m *Event) GetInverseOffers() *Event_InverseOffers {
	if m != nil {
		return m.InverseOffers
	}
	return nil
}

func (m *Event) GetRescind() *Event_Rescind {
	if m != nil {
		return m.Rescind
	}
	return nil
}

func (m *Event) GetRescindInverseOffer() *Event_RescindInverseOffer {
	if m != nil {
		return m.RescindInverseOffer
	}
	return nil
}

func (m *Event) GetUpdate() *Event_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *Event) GetUpdateOperationStatus() *Event_UpdateOperationStatus {
	if m != nil {
		return m.UpdateOperationStatus
	}
	return nil
}

func (m *Event) GetMessage() *Event_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Event) GetFailure() *Event_Failure {
	if m != nil {
		return m.Failure
	}
	return nil
}

func (m *Event) GetError() *Event_Error {
	if m != nil {
		return m.Error
	}
	return nil
}

// First event received when the scheduler subscribes.
type Event_Subscribed struct {
	FrameworkId *FrameworkID `protobuf:"bytes,1,req,name=framework_id,json=frameworkId" json:"framework_id,omitempty"`
	// This value will be set if the master is sending heartbeats. See
	// the comment above on 'HEARTBEAT' for more details.
	HeartbeatIntervalSeconds *float64 `protobuf:"fixed64,2,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds" json:"heartbeat_interval_seconds,omitempty"`
	// Since Mesos 1.1.
	MasterInfo           *MasterInfo `protobuf:"bytes,3,opt,name=master_info,json=masterInfo" json:"master_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Event_Subscribed) Reset()         { *m = Event_Subscribed{} }
func (m *Event_Subscribed) String() string { return proto.CompactTextString(m) }
func (*Event_Subscribed) ProtoMessage()    {}
func (*Event_Subscribed) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{0, 0}
}

func (m *Event_Subscribed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_Subscribed.Unmarshal(m, b)
}
func (m *Event_Subscribed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_Subscribed.Marshal(b, m, deterministic)
}
func (m *Event_Subscribed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_Subscribed.Merge(m, src)
}
func (m *Event_Subscribed) XXX_Size() int {
	return xxx_messageInfo_Event_Subscribed.Size(m)
}
func (m *Event_Subscribed) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_Subscribed.DiscardUnknown(m)
}

var xxx_messageInfo_Event_Subscribed proto.InternalMessageInfo

func (m *Event_Subscribed) GetFrameworkId() *FrameworkID {
	if m != nil {
		return m.FrameworkId
	}
	return nil
}

func (m *Event_Subscribed) GetHeartbeatIntervalSeconds() float64 {
	if m != nil && m.HeartbeatIntervalSeconds != nil {
		return *m.HeartbeatIntervalSeconds
	}
	return 0
}

func (m *Event_Subscribed) GetMasterInfo() *MasterInfo {
	if m != nil {
		return m.MasterInfo
	}
	return nil
}

// Received whenever there are new resources that are offered to the
// scheduler. Each offer corresponds to a set of resources on an
// agent. Until the scheduler accepts or declines an offer the
// resources are considered allocated to the scheduler.
type Event_Offers struct {
	Offers               []*Offer `protobuf:"bytes,1,rep,name=offers" json:"offers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event_Offers) Reset()         { *m = Event_Offers{} }
func (m *Event_Offers) String() string { return proto.CompactTextString(m) }
func (*Event_Offers) ProtoMessage()    {}
func (*Event_Offers) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{0, 1}
}

func (m *Event_Offers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_Offers.Unmarshal(m, b)
}
func (m *Event_Offers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_Offers.Marshal(b, m, deterministic)
}
func (m *Event_Offers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_Offers.Merge(m, src)
}
func (m *Event_Offers) XXX_Size() int {
	return xxx_messageInfo_Event_Offers.Size(m)
}
func (m *Event_Offers) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_Offers.DiscardUnknown(m)
}

var xxx_messageInfo_Event_Offers proto.InternalMessageInfo

func (m *Event_Offers) GetOffers() []*Offer {
	if m != nil {
		return m.Offers
	}
	return nil
}

// Received whenever there are resources requested back from the
// scheduler. Each inverse offer specifies the agent, and
// optionally specific resources. Accepting or Declining an inverse
// offer informs the allocator of the scheduler's ability to release
// the specified resources without violating an SLA. If no resources
// are specified then all resources on the agent are requested to be
// released.
type Event_InverseOffers struct {
	InverseOffers        []*InverseOffer `protobuf:"bytes,1,rep,name=inverse_offers,json=inverseOffers" json:"inverse_offers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Event_InverseOffers) Reset()         { *m = Event_InverseOffers{} }
func (m *Event_InverseOffers) String() string { return proto.CompactTextString(m) }
func (*Event_InverseOffers) ProtoMessage()    {}
func (*Event_InverseOffers) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{0, 2}
}

func (m *Event_InverseOffers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_InverseOffers.Unmarshal(m, b)
}
func (m *Event_InverseOffers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_InverseOffers.Marshal(b, m, deterministic)
}
func (m *Event_InverseOffers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_InverseOffers.Merge(m, src)
}
func (m *Event_InverseOffers) XXX_Size() int {
	return xxx_messageInfo_Event_InverseOffers.Size(m)
}
func (m *Event_InverseOffers) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_InverseOffers.DiscardUnknown(m)
}

var xxx_messageInfo_Event_InverseOffers proto.InternalMessageInfo

func (m *Event_InverseOffers) GetInverseOffers() []*InverseOffer {
	if m != nil {
		return m.InverseOffers
	}
	return nil
}

// Received when a particular offer is no longer valid (e.g., the
// agent corresponding to the offer has been removed) and hence
// needs to be rescinded. Any future calls ('Accept' / 'Decline') made
// by the scheduler regarding this offer will be invalid.
type Event_Rescind struct {
	OfferId              *OfferID `protobuf:"bytes,1,req,name=offer_id,json=offerId" json:"offer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event_Rescind) Reset()         { *m = Event_Rescind{} }
func (m *Event_Rescind) String() string { return proto.CompactTextString(m) }
func (*Event_Rescind) ProtoMessage()    {}
func (*Event_Rescind) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{0, 3}
}

func (m *Event_Rescind) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_Rescind.Unmarshal(m, b)
}
func (m *Event_Rescind) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_Rescind.Marshal(b, m, deterministic)
}
func (m *Event_Rescind) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_Rescind.Merge(m, src)
}
func (m *Event_Rescind) XXX_Size() int {
	return xxx_messageInfo_Event_Rescind.Size(m)
}
func (m *Event_Rescind) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_Rescind.DiscardUnknown(m)
}

var xxx_messageInfo_Event_Rescind proto.InternalMessageInfo

func (m *Event_Rescind) GetOfferId() *OfferID {
	if m != nil {
		return m.OfferId
	}
	return nil
}

// Received when a particular inverse offer is no longer valid
// (e.g., the agent corresponding to the offer has been removed)
// and hence needs to be rescinded. Any future calls ('Accept' /
// 'Decline') made by the scheduler regarding this inverse offer
// will be invalid.
type Event_RescindInverseOffer struct {
	InverseOfferId       *OfferID `protobuf:"bytes,1,req,name=inverse_offer_id,json=inverseOfferId" json:"inverse_offer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event_RescindInverseOffer) Reset()         { *m = Event_RescindInverseOffer{} }
func (m *Event_RescindInverseOffer) String() string { return proto.CompactTextString(m) }
func (*Event_RescindInverseOffer) ProtoMessage()    {}
func (*Event_RescindInverseOffer) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{0, 4}
}

func (m *Event_RescindInverseOffer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_RescindInverseOffer.Unmarshal(m, b)
}
func (m *Event_RescindInverseOffer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_RescindInverseOffer.Marshal(b, m, deterministic)
}
func (m *Event_RescindInverseOffer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_RescindInverseOffer.Merge(m, src)
}
func (m *Event_RescindInverseOffer) XXX_Size() int {
	return xxx_messageInfo_Event_RescindInverseOffer.Size(m)
}
func (m *Event_RescindInverseOffer) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_RescindInverseOffer.DiscardUnknown(m)
}

var xxx_messageInfo_Event_RescindInverseOffer proto.InternalMessageInfo

func (m *Event_RescindInverseOffer) GetInverseOfferId() *OfferID {
	if m != nil {
		return m.InverseOfferId
	}
	return nil
}

// Received whenever there is a status update that is generated by
// the executor or agent or master. Status updates should be used by
// executors to reliably communicate the status of the tasks that
// they manage. It is crucial that a terminal update (see TaskState
// in v1/mesos.proto) is sent by the executor as soon as the task
// terminates, in order for Mesos to release the resources allocated
// to the task. It is also the responsibility of the scheduler to
// explicitly acknowledge the receipt of a status update. See
// 'Acknowledge' in the 'Call' section below for the semantics.
//
// A task status update may be used for guaranteed delivery of some
// task-related information, e.g., task's health update. Such
// information may be shadowed by subsequent task status updates, that
// do not preserve fields of the previously sent message.
type Event_Update struct {
	Status               *TaskStatus `protobuf:"bytes,1,req,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Event_Update) Reset()         { *m = Event_Update{} }
func (m *Event_Update) String() string { return proto.CompactTextString(m) }
func (*Event_Update) ProtoMessage()    {}
func (*Event_Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{0, 5}
}

func (m *Event_Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_Update.Unmarshal(m, b)
}
func (m *Event_Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_Update.Marshal(b, m, deterministic)
}
func (m *Event_Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_Update.Merge(m, src)
}
func (m *Event_Update) XXX_Size() int {
	return xxx_messageInfo_Event_Update.Size(m)
}
func (m *Event_Update) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_Update.DiscardUnknown(m)
}

var xxx_messageInfo_Event_Update proto.InternalMessageInfo

func (m *Event_Update) GetStatus() *TaskStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// EXPERIMENTAL.
//
// Received when there is an operation status update generated by the
// master, agent, or resource provider. These updates are only sent to
// the framework for operations which had the operation ID set by the
// framework. It is the responsibility of the scheduler to explicitly
// acknowledge the receipt of a status update.
// See 'AcknowledgeOperationStatus' in the 'Call' section below for
// the semantics.
type Event_UpdateOperationStatus struct {
	Status               *OperationStatus `protobuf:"bytes,1,req,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Event_UpdateOperationStatus) Reset()         { *m = Event_UpdateOperationStatus{} }
func (m *Event_UpdateOperationStatus) String() string { return proto.CompactTextString(m) }
func (*Event_UpdateOperationStatus) ProtoMessage()    {}
func (*Event_UpdateOperationStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{0, 6}
}

func (m *Event_UpdateOperationStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_UpdateOperationStatus.Unmarshal(m, b)
}
func (m *Event_UpdateOperationStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_UpdateOperationStatus.Marshal(b, m, deterministic)
}
func (m *Event_UpdateOperationStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_UpdateOperationStatus.Merge(m, src)
}
func (m *Event_UpdateOperationStatus) XXX_Size() int {
	return xxx_messageInfo_Event_UpdateOperationStatus.Size(m)
}
func (m *Event_UpdateOperationStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_UpdateOperationStatus.DiscardUnknown(m)
}

var xxx_messageInfo_Event_UpdateOperationStatus proto.InternalMessageInfo

func (m *Event_UpdateOperationStatus) GetStatus() *OperationStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// Received when a custom message generated by the executor is
// forwarded by the master. Note that this message is not
// interpreted by Mesos and is only forwarded (without reliability
// guarantees) to the scheduler. It is up to the executor to retry
// if the message is dropped for any reason.
type Event_Message struct {
	AgentId              *AgentID    `protobuf:"bytes,1,req,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	ExecutorId           *ExecutorID `protobuf:"bytes,2,req,name=executor_id,json=executorId" json:"executor_id,omitempty"`
	Data                 []byte      `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Event_Message) Reset()         { *m = Event_Message{} }
func (m *Event_Message) String() string { return proto.CompactTextString(m) }
func (*Event_Message) ProtoMessage()    {}
func (*Event_Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{0, 7}
}

func (m *Event_Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_Message.Unmarshal(m, b)
}
func (m *Event_Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_Message.Marshal(b, m, deterministic)
}
func (m *Event_Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_Message.Merge(m, src)
}
func (m *Event_Message) XXX_Size() int {
	return xxx_messageInfo_Event_Message.Size(m)
}
func (m *Event_Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Event_Message proto.InternalMessageInfo

func (m *Event_Message) GetAgentId() *AgentID {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *Event_Message) GetExecutorId() *ExecutorID {
	if m != nil {
		return m.ExecutorId
	}
	return nil
}

func (m *Event_Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// Received when an agent is removed from the cluster (e.g., failed
// health checks) or when an executor is terminated. Note that, this
// event coincides with receipt of terminal UPDATE events for any
// active tasks belonging to the agent or executor and receipt of
// 'Rescind' events for any outstanding offers belonging to the
// agent. Note that there is no guaranteed order between the
// 'Failure', 'Update' and 'Rescind' events when an agent or executor
// is removed.
// TODO(vinod): Consider splitting the lost agent and terminated
// executor into separate events and ensure it's reliably generated.
type Event_Failure struct {
	AgentId *AgentID `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	// If this was just a failure of an executor on an agent then
	// 'executor_id' will be set and possibly 'status' (if we were
	// able to determine the exit status).
	ExecutorId *ExecutorID `protobuf:"bytes,2,opt,name=executor_id,json=executorId" json:"executor_id,omitempty"`
	// On Posix, `status` corresponds to termination information in the
	// `stat_loc` area returned from a `waitpid` call. On Windows, `status`
	// is obtained via calling the `GetExitCodeProcess()` function. For
	// messages coming from Posix agents, schedulers need to apply
	// `WEXITSTATUS` family macros or equivalent transformations to obtain
	// exit codes.
	//
	// TODO(alexr): Consider unifying Windows and Posix behavior by returning
	// exit code here, see MESOS-7241.
	Status               *int32   `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event_Failure) Reset()         { *m = Event_Failure{} }
func (m *Event_Failure) String() string { return proto.CompactTextString(m) }
func (*Event_Failure) ProtoMessage()    {}
func (*Event_Failure) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{0, 8}
}

func (m *Event_Failure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_Failure.Unmarshal(m, b)
}
func (m *Event_Failure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_Failure.Marshal(b, m, deterministic)
}
func (m *Event_Failure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_Failure.Merge(m, src)
}
func (m *Event_Failure) XXX_Size() int {
	return xxx_messageInfo_Event_Failure.Size(m)
}
func (m *Event_Failure) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_Failure.DiscardUnknown(m)
}

var xxx_messageInfo_Event_Failure proto.InternalMessageInfo

func (m *Event_Failure) GetAgentId() *AgentID {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *Event_Failure) GetExecutorId() *ExecutorID {
	if m != nil {
		return m.ExecutorId
	}
	return nil
}

func (m *Event_Failure) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

// Received when there is an unrecoverable error in the scheduler (e.g.,
// scheduler failed over, rate limiting, authorization errors etc.). The
// scheduler should abort on receiving this event.
type Event_Error struct {
	Message              *string  `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event_Error) Reset()         { *m = Event_Error{} }
func (m *Event_Error) String() string { return proto.CompactTextString(m) }
func (*Event_Error) ProtoMessage()    {}
func (*Event_Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{0, 9}
}

func (m *Event_Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_Error.Unmarshal(m, b)
}
func (m *Event_Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_Error.Marshal(b, m, deterministic)
}
func (m *Event_Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_Error.Merge(m, src)
}
func (m *Event_Error) XXX_Size() int {
	return xxx_messageInfo_Event_Error.Size(m)
}
func (m *Event_Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Event_Error proto.InternalMessageInfo

func (m *Event_Error) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

//*
// NOTE: After resolution of MESOS-9648, this message is not currently used by
// Mesos. It is left in place in anticipation of future use.
//
// Synchronous responses for calls made to the scheduler API.
type Response struct {
	Type *Response_Type `protobuf:"varint,1,opt,name=type,enum=mesos.v1.Response_Type" json:"type,omitempty"`
	// DEPRECATED.
	ReconcileOperations  *Response_ReconcileOperations `protobuf:"bytes,2,opt,name=reconcile_operations,json=reconcileOperations" json:"reconcile_operations,omitempty"` // Deprecated: Do not use.
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetType() Response_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Response_UNKNOWN
}

// Deprecated: Do not use.
func (m *Response) GetReconcileOperations() *Response_ReconcileOperations {
	if m != nil {
		return m.ReconcileOperations
	}
	return nil
}

// DEPRECATED.
type Response_ReconcileOperations struct {
	OperationStatuses    []*OperationStatus `protobuf:"bytes,1,rep,name=operation_statuses,json=operationStatuses" json:"operation_statuses,omitempty"` // Deprecated: Do not use.
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Response_ReconcileOperations) Reset()         { *m = Response_ReconcileOperations{} }
func (m *Response_ReconcileOperations) String() string { return proto.CompactTextString(m) }
func (*Response_ReconcileOperations) ProtoMessage()    {}
func (*Response_ReconcileOperations) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{1, 0}
}

func (m *Response_ReconcileOperations) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_ReconcileOperations.Unmarshal(m, b)
}
func (m *Response_ReconcileOperations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_ReconcileOperations.Marshal(b, m, deterministic)
}
func (m *Response_ReconcileOperations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_ReconcileOperations.Merge(m, src)
}
func (m *Response_ReconcileOperations) XXX_Size() int {
	return xxx_messageInfo_Response_ReconcileOperations.Size(m)
}
func (m *Response_ReconcileOperations) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_ReconcileOperations.DiscardUnknown(m)
}

var xxx_messageInfo_Response_ReconcileOperations proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *Response_ReconcileOperations) GetOperationStatuses() []*OperationStatus {
	if m != nil {
		return m.OperationStatuses
	}
	return nil
}

//*
// Scheduler call API.
//
// Like Event, a Call is described using the standard protocol buffer
// "union" trick (see above).
type Call struct {
	// Identifies who generated this call. Master assigns a framework id
	// when a new scheduler subscribes for the first time. Once assigned,
	// the scheduler must set the 'framework_id' here and within its
	// FrameworkInfo (in any further 'Subscribe' calls). This allows the
	// master to identify a scheduler correctly across disconnections,
	// failovers, etc.
	FrameworkId *FrameworkID `protobuf:"bytes,1,opt,name=framework_id,json=frameworkId" json:"framework_id,omitempty"`
	// Type of the call, indicates which optional field below should be
	// present if that type has a nested message definition.
	// See comments on `Event::Type` above on the reasoning behind this
	// field being optional.
	Type                       *Call_Type                       `protobuf:"varint,2,opt,name=type,enum=mesos.v1.Call_Type" json:"type,omitempty"`
	Subscribe                  *Call_Subscribe                  `protobuf:"bytes,3,opt,name=subscribe" json:"subscribe,omitempty"`
	Accept                     *Call_Accept                     `protobuf:"bytes,4,opt,name=accept" json:"accept,omitempty"`
	Decline                    *Call_Decline                    `protobuf:"bytes,5,opt,name=decline" json:"decline,omitempty"`
	AcceptInverseOffers        *Call_AcceptInverseOffers        `protobuf:"bytes,13,opt,name=accept_inverse_offers,json=acceptInverseOffers" json:"accept_inverse_offers,omitempty"`
	DeclineInverseOffers       *Call_DeclineInverseOffers       `protobuf:"bytes,14,opt,name=decline_inverse_offers,json=declineInverseOffers" json:"decline_inverse_offers,omitempty"`
	Revive                     *Call_Revive                     `protobuf:"bytes,15,opt,name=revive" json:"revive,omitempty"`
	Kill                       *Call_Kill                       `protobuf:"bytes,6,opt,name=kill" json:"kill,omitempty"`
	Shutdown                   *Call_Shutdown                   `protobuf:"bytes,7,opt,name=shutdown" json:"shutdown,omitempty"`
	Acknowledge                *Call_Acknowledge                `protobuf:"bytes,8,opt,name=acknowledge" json:"acknowledge,omitempty"`
	AcknowledgeOperationStatus *Call_AcknowledgeOperationStatus `protobuf:"bytes,17,opt,name=acknowledge_operation_status,json=acknowledgeOperationStatus" json:"acknowledge_operation_status,omitempty"`
	Reconcile                  *Call_Reconcile                  `protobuf:"bytes,9,opt,name=reconcile" json:"reconcile,omitempty"`
	ReconcileOperations        *Call_ReconcileOperations        `protobuf:"bytes,18,opt,name=reconcile_operations,json=reconcileOperations" json:"reconcile_operations,omitempty"`
	Message                    *Call_Message                    `protobuf:"bytes,10,opt,name=message" json:"message,omitempty"`
	Request                    *Call_Request                    `protobuf:"bytes,11,opt,name=request" json:"request,omitempty"`
	Suppress                   *Call_Suppress                   `protobuf:"bytes,16,opt,name=suppress" json:"suppress,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                         `json:"-"`
	XXX_unrecognized           []byte                           `json:"-"`
	XXX_sizecache              int32                            `json:"-"`
}

func (m *Call) Reset()         { *m = Call{} }
func (m *Call) String() string { return proto.CompactTextString(m) }
func (*Call) ProtoMessage()    {}
func (*Call) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{2}
}

func (m *Call) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call.Unmarshal(m, b)
}
func (m *Call) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call.Marshal(b, m, deterministic)
}
func (m *Call) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call.Merge(m, src)
}
func (m *Call) XXX_Size() int {
	return xxx_messageInfo_Call.Size(m)
}
func (m *Call) XXX_DiscardUnknown() {
	xxx_messageInfo_Call.DiscardUnknown(m)
}

var xxx_messageInfo_Call proto.InternalMessageInfo

func (m *Call) GetFrameworkId() *FrameworkID {
	if m != nil {
		return m.FrameworkId
	}
	return nil
}

func (m *Call) GetType() Call_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Call_UNKNOWN
}

func (m *Call) GetSubscribe() *Call_Subscribe {
	if m != nil {
		return m.Subscribe
	}
	return nil
}

func (m *Call) GetAccept() *Call_Accept {
	if m != nil {
		return m.Accept
	}
	return nil
}

func (m *Call) GetDecline() *Call_Decline {
	if m != nil {
		return m.Decline
	}
	return nil
}

func (m *Call) GetAcceptInverseOffers() *Call_AcceptInverseOffers {
	if m != nil {
		return m.AcceptInverseOffers
	}
	return nil
}

func (m *Call) GetDeclineInverseOffers() *Call_DeclineInverseOffers {
	if m != nil {
		return m.DeclineInverseOffers
	}
	return nil
}

func (m *Call) GetRevive() *Call_Revive {
	if m != nil {
		return m.Revive
	}
	return nil
}

func (m *Call) GetKill() *Call_Kill {
	if m != nil {
		return m.Kill
	}
	return nil
}

func (m *Call) GetShutdown() *Call_Shutdown {
	if m != nil {
		return m.Shutdown
	}
	return nil
}

func (m *Call) GetAcknowledge() *Call_Acknowledge {
	if m != nil {
		return m.Acknowledge
	}
	return nil
}

func (m *Call) GetAcknowledgeOperationStatus() *Call_AcknowledgeOperationStatus {
	if m != nil {
		return m.AcknowledgeOperationStatus
	}
	return nil
}

func (m *Call) GetReconcile() *Call_Reconcile {
	if m != nil {
		return m.Reconcile
	}
	return nil
}

func (m *Call) GetReconcileOperations() *Call_ReconcileOperations {
	if m != nil {
		return m.ReconcileOperations
	}
	return nil
}

func (m *Call) GetMessage() *Call_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Call) GetRequest() *Call_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Call) GetSuppress() *Call_Suppress {
	if m != nil {
		return m.Suppress
	}
	return nil
}

// Subscribes the scheduler with the master to receive events. A
// scheduler must send other calls only after it has received the
// SUBCRIBED event.
type Call_Subscribe struct {
	// See the comments below on 'framework_id' on the semantics for
	// 'framework_info.id'.
	FrameworkInfo *FrameworkInfo `protobuf:"bytes,1,req,name=framework_info,json=frameworkInfo" json:"framework_info,omitempty"`
	// List of suppressed roles for which the framework does not wish to be
	// offered resources. The framework can decide to suppress all or a subset
	// of roles the framework (re)registers as.
	SuppressedRoles      []string `protobuf:"bytes,2,rep,name=suppressed_roles,json=suppressedRoles" json:"suppressed_roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Call_Subscribe) Reset()         { *m = Call_Subscribe{} }
func (m *Call_Subscribe) String() string { return proto.CompactTextString(m) }
func (*Call_Subscribe) ProtoMessage()    {}
func (*Call_Subscribe) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{2, 0}
}

func (m *Call_Subscribe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call_Subscribe.Unmarshal(m, b)
}
func (m *Call_Subscribe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call_Subscribe.Marshal(b, m, deterministic)
}
func (m *Call_Subscribe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call_Subscribe.Merge(m, src)
}
func (m *Call_Subscribe) XXX_Size() int {
	return xxx_messageInfo_Call_Subscribe.Size(m)
}
func (m *Call_Subscribe) XXX_DiscardUnknown() {
	xxx_messageInfo_Call_Subscribe.DiscardUnknown(m)
}

var xxx_messageInfo_Call_Subscribe proto.InternalMessageInfo

func (m *Call_Subscribe) GetFrameworkInfo() *FrameworkInfo {
	if m != nil {
		return m.FrameworkInfo
	}
	return nil
}

func (m *Call_Subscribe) GetSuppressedRoles() []string {
	if m != nil {
		return m.SuppressedRoles
	}
	return nil
}

// Accepts an offer, performing the specified operations
// in a sequential manner.
//
// E.g. Launch a task with a newly reserved persistent volume:
//
//   Accept {
//     offer_ids: [ ... ]
//     operations: [
//       { type: RESERVE,
//         reserve: { resources: [ disk(role):2 ] } }
//       { type: CREATE,
//         create: { volumes: [ disk(role):1+persistence ] } }
//       { type: LAUNCH,
//         launch: { task_infos ... disk(role):1;disk(role):1+persistence } }
//     ]
//   }
//
// Note that any of the offer's resources not used in the 'Accept'
// call (e.g., to launch a task) are considered unused and might be
// reoffered to other frameworks. In other words, the same OfferID
// cannot be used in more than one 'Accept' call.
type Call_Accept struct {
	OfferIds             []*OfferID         `protobuf:"bytes,1,rep,name=offer_ids,json=offerIds" json:"offer_ids,omitempty"`
	Operations           []*Offer_Operation `protobuf:"bytes,2,rep,name=operations" json:"operations,omitempty"`
	Filters              *Filters           `protobuf:"bytes,3,opt,name=filters" json:"filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Call_Accept) Reset()         { *m = Call_Accept{} }
func (m *Call_Accept) String() string { return proto.CompactTextString(m) }
func (*Call_Accept) ProtoMessage()    {}
func (*Call_Accept) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{2, 1}
}

func (m *Call_Accept) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call_Accept.Unmarshal(m, b)
}
func (m *Call_Accept) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call_Accept.Marshal(b, m, deterministic)
}
func (m *Call_Accept) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call_Accept.Merge(m, src)
}
func (m *Call_Accept) XXX_Size() int {
	return xxx_messageInfo_Call_Accept.Size(m)
}
func (m *Call_Accept) XXX_DiscardUnknown() {
	xxx_messageInfo_Call_Accept.DiscardUnknown(m)
}

var xxx_messageInfo_Call_Accept proto.InternalMessageInfo

func (m *Call_Accept) GetOfferIds() []*OfferID {
	if m != nil {
		return m.OfferIds
	}
	return nil
}

func (m *Call_Accept) GetOperations() []*Offer_Operation {
	if m != nil {
		return m.Operations
	}
	return nil
}

func (m *Call_Accept) GetFilters() *Filters {
	if m != nil {
		return m.Filters
	}
	return nil
}

// Declines an offer, signaling the master to potentially reoffer
// the resources to a different framework. Note that this is same
// as sending an Accept call with no operations. See comments on
// top of 'Accept' for semantics.
type Call_Decline struct {
	OfferIds             []*OfferID `protobuf:"bytes,1,rep,name=offer_ids,json=offerIds" json:"offer_ids,omitempty"`
	Filters              *Filters   `protobuf:"bytes,2,opt,name=filters" json:"filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Call_Decline) Reset()         { *m = Call_Decline{} }
func (m *Call_Decline) String() string { return proto.CompactTextString(m) }
func (*Call_Decline) ProtoMessage()    {}
func (*Call_Decline) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{2, 2}
}

func (m *Call_Decline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call_Decline.Unmarshal(m, b)
}
func (m *Call_Decline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call_Decline.Marshal(b, m, deterministic)
}
func (m *Call_Decline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call_Decline.Merge(m, src)
}
func (m *Call_Decline) XXX_Size() int {
	return xxx_messageInfo_Call_Decline.Size(m)
}
func (m *Call_Decline) XXX_DiscardUnknown() {
	xxx_messageInfo_Call_Decline.DiscardUnknown(m)
}

var xxx_messageInfo_Call_Decline proto.InternalMessageInfo

func (m *Call_Decline) GetOfferIds() []*OfferID {
	if m != nil {
		return m.OfferIds
	}
	return nil
}

func (m *Call_Decline) GetFilters() *Filters {
	if m != nil {
		return m.Filters
	}
	return nil
}

// Accepts an inverse offer. Inverse offers should only be accepted
// if the resources in the offer can be safely evacuated before the
// provided unavailability.
type Call_AcceptInverseOffers struct {
	InverseOfferIds      []*OfferID `protobuf:"bytes,1,rep,name=inverse_offer_ids,json=inverseOfferIds" json:"inverse_offer_ids,omitempty"`
	Filters              *Filters   `protobuf:"bytes,2,opt,name=filters" json:"filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Call_AcceptInverseOffers) Reset()         { *m = Call_AcceptInverseOffers{} }
func (m *Call_AcceptInverseOffers) String() string { return proto.CompactTextString(m) }
func (*Call_AcceptInverseOffers) ProtoMessage()    {}
func (*Call_AcceptInverseOffers) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{2, 3}
}

func (m *Call_AcceptInverseOffers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call_AcceptInverseOffers.Unmarshal(m, b)
}
func (m *Call_AcceptInverseOffers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call_AcceptInverseOffers.Marshal(b, m, deterministic)
}
func (m *Call_AcceptInverseOffers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call_AcceptInverseOffers.Merge(m, src)
}
func (m *Call_AcceptInverseOffers) XXX_Size() int {
	return xxx_messageInfo_Call_AcceptInverseOffers.Size(m)
}
func (m *Call_AcceptInverseOffers) XXX_DiscardUnknown() {
	xxx_messageInfo_Call_AcceptInverseOffers.DiscardUnknown(m)
}

var xxx_messageInfo_Call_AcceptInverseOffers proto.InternalMessageInfo

func (m *Call_AcceptInverseOffers) GetInverseOfferIds() []*OfferID {
	if m != nil {
		return m.InverseOfferIds
	}
	return nil
}

func (m *Call_AcceptInverseOffers) GetFilters() *Filters {
	if m != nil {
		return m.Filters
	}
	return nil
}

// Declines an inverse offer. Inverse offers should be declined if
// the resources in the offer might not be safely evacuated before
// the provided unavailability.
type Call_DeclineInverseOffers struct {
	InverseOfferIds      []*OfferID `protobuf:"bytes,1,rep,name=inverse_offer_ids,json=inverseOfferIds" json:"inverse_offer_ids,omitempty"`
	Filters              *Filters   `protobuf:"bytes,2,opt,name=filters" json:"filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Call_DeclineInverseOffers) Reset()         { *m = Call_DeclineInverseOffers{} }
func (m *Call_DeclineInverseOffers) String() string { return proto.CompactTextString(m) }
func (*Call_DeclineInverseOffers) ProtoMessage()    {}
func (*Call_DeclineInverseOffers) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{2, 4}
}

func (m *Call_DeclineInverseOffers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call_DeclineInverseOffers.Unmarshal(m, b)
}
func (m *Call_DeclineInverseOffers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call_DeclineInverseOffers.Marshal(b, m, deterministic)
}
func (m *Call_DeclineInverseOffers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call_DeclineInverseOffers.Merge(m, src)
}
func (m *Call_DeclineInverseOffers) XXX_Size() int {
	return xxx_messageInfo_Call_DeclineInverseOffers.Size(m)
}
func (m *Call_DeclineInverseOffers) XXX_DiscardUnknown() {
	xxx_messageInfo_Call_DeclineInverseOffers.DiscardUnknown(m)
}

var xxx_messageInfo_Call_DeclineInverseOffers proto.InternalMessageInfo

func (m *Call_DeclineInverseOffers) GetInverseOfferIds() []*OfferID {
	if m != nil {
		return m.InverseOfferIds
	}
	return nil
}

func (m *Call_DeclineInverseOffers) GetFilters() *Filters {
	if m != nil {
		return m.Filters
	}
	return nil
}

// Revive offers for the specified roles. If `roles` is empty,
// the `REVIVE` call will revive offers for all of the roles
// the framework is currently subscribed to.
type Call_Revive struct {
	Roles                []string `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Call_Revive) Reset()         { *m = Call_Revive{} }
func (m *Call_Revive) String() string { return proto.CompactTextString(m) }
func (*Call_Revive) ProtoMessage()    {}
func (*Call_Revive) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{2, 5}
}

func (m *Call_Revive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call_Revive.Unmarshal(m, b)
}
func (m *Call_Revive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call_Revive.Marshal(b, m, deterministic)
}
func (m *Call_Revive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call_Revive.Merge(m, src)
}
func (m *Call_Revive) XXX_Size() int {
	return xxx_messageInfo_Call_Revive.Size(m)
}
func (m *Call_Revive) XXX_DiscardUnknown() {
	xxx_messageInfo_Call_Revive.DiscardUnknown(m)
}

var xxx_messageInfo_Call_Revive proto.InternalMessageInfo

func (m *Call_Revive) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

// Kills a specific task. If the scheduler has a custom executor,
// the kill is forwarded to the executor and it is up to the
// executor to kill the task and send a TASK_KILLED (or TASK_FAILED)
// update. Note that Mesos releases the resources for a task once it
// receives a terminal update (See TaskState in v1/mesos.proto) for
// it. If the task is unknown to the master, a TASK_LOST update is
// generated.
//
// If a task within a task group is killed before the group is
// delivered to the executor, all tasks in the task group are
// killed. When a task group has been delivered to the executor,
// it is up to the executor to decide how to deal with the kill.
// Note The default Mesos executor will currently kill all the
// tasks in the task group if it gets a kill for any task.
type Call_Kill struct {
	TaskId  *TaskID  `protobuf:"bytes,1,req,name=task_id,json=taskId" json:"task_id,omitempty"`
	AgentId *AgentID `protobuf:"bytes,2,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	// If set, overrides any previously specified kill policy for this task.
	// This includes 'TaskInfo.kill_policy' and 'Executor.kill.kill_policy'.
	// Can be used to forcefully kill a task which is already being killed.
	KillPolicy           *KillPolicy `protobuf:"bytes,3,opt,name=kill_policy,json=killPolicy" json:"kill_policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Call_Kill) Reset()         { *m = Call_Kill{} }
func (m *Call_Kill) String() string { return proto.CompactTextString(m) }
func (*Call_Kill) ProtoMessage()    {}
func (*Call_Kill) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{2, 6}
}

func (m *Call_Kill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call_Kill.Unmarshal(m, b)
}
func (m *Call_Kill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call_Kill.Marshal(b, m, deterministic)
}
func (m *Call_Kill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call_Kill.Merge(m, src)
}
func (m *Call_Kill) XXX_Size() int {
	return xxx_messageInfo_Call_Kill.Size(m)
}
func (m *Call_Kill) XXX_DiscardUnknown() {
	xxx_messageInfo_Call_Kill.DiscardUnknown(m)
}

var xxx_messageInfo_Call_Kill proto.InternalMessageInfo

func (m *Call_Kill) GetTaskId() *TaskID {
	if m != nil {
		return m.TaskId
	}
	return nil
}

func (m *Call_Kill) GetAgentId() *AgentID {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *Call_Kill) GetKillPolicy() *KillPolicy {
	if m != nil {
		return m.KillPolicy
	}
	return nil
}

// Shuts down a custom executor. When the executor gets a shutdown
// event, it is expected to kill all its tasks (and send TASK_KILLED
// updates) and terminate. If the executor doesn't terminate within
// a certain timeout (configurable via
// '--executor_shutdown_grace_period' agent flag), the agent will
// forcefully destroy the container (executor and its tasks) and
// transition its active tasks to TASK_LOST.
type Call_Shutdown struct {
	ExecutorId           *ExecutorID `protobuf:"bytes,1,req,name=executor_id,json=executorId" json:"executor_id,omitempty"`
	AgentId              *AgentID    `protobuf:"bytes,2,req,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Call_Shutdown) Reset()         { *m = Call_Shutdown{} }
func (m *Call_Shutdown) String() string { return proto.CompactTextString(m) }
func (*Call_Shutdown) ProtoMessage()    {}
func (*Call_Shutdown) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{2, 7}
}

func (m *Call_Shutdown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call_Shutdown.Unmarshal(m, b)
}
func (m *Call_Shutdown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call_Shutdown.Marshal(b, m, deterministic)
}
func (m *Call_Shutdown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call_Shutdown.Merge(m, src)
}
func (m *Call_Shutdown) XXX_Size() int {
	return xxx_messageInfo_Call_Shutdown.Size(m)
}
func (m *Call_Shutdown) XXX_DiscardUnknown() {
	xxx_messageInfo_Call_Shutdown.DiscardUnknown(m)
}

var xxx_messageInfo_Call_Shutdown proto.InternalMessageInfo

func (m *Call_Shutdown) GetExecutorId() *ExecutorID {
	if m != nil {
		return m.ExecutorId
	}
	return nil
}

func (m *Call_Shutdown) GetAgentId() *AgentID {
	if m != nil {
		return m.AgentId
	}
	return nil
}

// Acknowledges the receipt of status update. Schedulers are
// responsible for explicitly acknowledging the receipt of status
// updates that have 'Update.status().uuid()' field set. Such status
// updates are retried by the agent until they are acknowledged by
// the scheduler.
type Call_Acknowledge struct {
	AgentId              *AgentID `protobuf:"bytes,1,req,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	TaskId               *TaskID  `protobuf:"bytes,2,req,name=task_id,json=taskId" json:"task_id,omitempty"`
	Uuid                 []byte   `protobuf:"bytes,3,req,name=uuid" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Call_Acknowledge) Reset()         { *m = Call_Acknowledge{} }
func (m *Call_Acknowledge) String() string { return proto.CompactTextString(m) }
func (*Call_Acknowledge) ProtoMessage()    {}
func (*Call_Acknowledge) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{2, 8}
}

func (m *Call_Acknowledge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call_Acknowledge.Unmarshal(m, b)
}
func (m *Call_Acknowledge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call_Acknowledge.Marshal(b, m, deterministic)
}
func (m *Call_Acknowledge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call_Acknowledge.Merge(m, src)
}
func (m *Call_Acknowledge) XXX_Size() int {
	return xxx_messageInfo_Call_Acknowledge.Size(m)
}
func (m *Call_Acknowledge) XXX_DiscardUnknown() {
	xxx_messageInfo_Call_Acknowledge.DiscardUnknown(m)
}

var xxx_messageInfo_Call_Acknowledge proto.InternalMessageInfo

func (m *Call_Acknowledge) GetAgentId() *AgentID {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *Call_Acknowledge) GetTaskId() *TaskID {
	if m != nil {
		return m.TaskId
	}
	return nil
}

func (m *Call_Acknowledge) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

// EXPERIMENTAL.
//
// Acknowledges the receipt of an operation status update. Schedulers
// are responsible for explicitly acknowledging the receipt of updates
// which have the 'UpdateOperationStatus.status().uuid()' field set.
// Such status updates are retried by the agent or resource provider
// until they are acknowledged by the scheduler.
type Call_AcknowledgeOperationStatus struct {
	// If the operation affects resources that belong to a SLRP, both
	// `agent_id` and `resource_provider_id` have to be set.
	//
	// If the operation affects resources that belong to a SERP, only
	// `resource_provider_id` has to be set.
	AgentId              *AgentID            `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	ResourceProviderId   *ResourceProviderID `protobuf:"bytes,2,opt,name=resource_provider_id,json=resourceProviderId" json:"resource_provider_id,omitempty"`
	Uuid                 []byte              `protobuf:"bytes,3,req,name=uuid" json:"uuid,omitempty"`
	OperationId          *OperationID        `protobuf:"bytes,4,req,name=operation_id,json=operationId" json:"operation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Call_AcknowledgeOperationStatus) Reset()         { *m = Call_AcknowledgeOperationStatus{} }
func (m *Call_AcknowledgeOperationStatus) String() string { return proto.CompactTextString(m) }
func (*Call_AcknowledgeOperationStatus) ProtoMessage()    {}
func (*Call_AcknowledgeOperationStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{2, 9}
}

func (m *Call_AcknowledgeOperationStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call_AcknowledgeOperationStatus.Unmarshal(m, b)
}
func (m *Call_AcknowledgeOperationStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call_AcknowledgeOperationStatus.Marshal(b, m, deterministic)
}
func (m *Call_AcknowledgeOperationStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call_AcknowledgeOperationStatus.Merge(m, src)
}
func (m *Call_AcknowledgeOperationStatus) XXX_Size() int {
	return xxx_messageInfo_Call_AcknowledgeOperationStatus.Size(m)
}
func (m *Call_AcknowledgeOperationStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_Call_AcknowledgeOperationStatus.DiscardUnknown(m)
}

var xxx_messageInfo_Call_AcknowledgeOperationStatus proto.InternalMessageInfo

func (m *Call_AcknowledgeOperationStatus) GetAgentId() *AgentID {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *Call_AcknowledgeOperationStatus) GetResourceProviderId() *ResourceProviderID {
	if m != nil {
		return m.ResourceProviderId
	}
	return nil
}

func (m *Call_AcknowledgeOperationStatus) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *Call_AcknowledgeOperationStatus) GetOperationId() *OperationID {
	if m != nil {
		return m.OperationId
	}
	return nil
}

// Allows the scheduler to query the status for non-terminal tasks.
// This causes the master to send back the latest task status for
// each task in 'tasks', if possible. Tasks that are no longer known
// will result in a TASK_LOST, TASK_UNKNOWN, or TASK_UNREACHABLE update.
// If 'tasks' is empty, then the master will send the latest status
// for each task currently known.
type Call_Reconcile struct {
	Tasks                []*Call_Reconcile_Task `protobuf:"bytes,1,rep,name=tasks" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Call_Reconcile) Reset()         { *m = Call_Reconcile{} }
func (m *Call_Reconcile) String() string { return proto.CompactTextString(m) }
func (*Call_Reconcile) ProtoMessage()    {}
func (*Call_Reconcile) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{2, 10}
}

func (m *Call_Reconcile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call_Reconcile.Unmarshal(m, b)
}
func (m *Call_Reconcile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call_Reconcile.Marshal(b, m, deterministic)
}
func (m *Call_Reconcile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call_Reconcile.Merge(m, src)
}
func (m *Call_Reconcile) XXX_Size() int {
	return xxx_messageInfo_Call_Reconcile.Size(m)
}
func (m *Call_Reconcile) XXX_DiscardUnknown() {
	xxx_messageInfo_Call_Reconcile.DiscardUnknown(m)
}

var xxx_messageInfo_Call_Reconcile proto.InternalMessageInfo

func (m *Call_Reconcile) GetTasks() []*Call_Reconcile_Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

// TODO(vinod): Support arbitrary queries than just state of tasks.
type Call_Reconcile_Task struct {
	TaskId               *TaskID  `protobuf:"bytes,1,req,name=task_id,json=taskId" json:"task_id,omitempty"`
	AgentId              *AgentID `protobuf:"bytes,2,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Call_Reconcile_Task) Reset()         { *m = Call_Reconcile_Task{} }
func (m *Call_Reconcile_Task) String() string { return proto.CompactTextString(m) }
func (*Call_Reconcile_Task) ProtoMessage()    {}
func (*Call_Reconcile_Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{2, 10, 0}
}

func (m *Call_Reconcile_Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call_Reconcile_Task.Unmarshal(m, b)
}
func (m *Call_Reconcile_Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call_Reconcile_Task.Marshal(b, m, deterministic)
}
func (m *Call_Reconcile_Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call_Reconcile_Task.Merge(m, src)
}
func (m *Call_Reconcile_Task) XXX_Size() int {
	return xxx_messageInfo_Call_Reconcile_Task.Size(m)
}
func (m *Call_Reconcile_Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Call_Reconcile_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Call_Reconcile_Task proto.InternalMessageInfo

func (m *Call_Reconcile_Task) GetTaskId() *TaskID {
	if m != nil {
		return m.TaskId
	}
	return nil
}

func (m *Call_Reconcile_Task) GetAgentId() *AgentID {
	if m != nil {
		return m.AgentId
	}
	return nil
}

// EXPERIMENTAL.
//
// Allows the scheduler to query the status of operations. This causes
// the master to send back the latest status for each operation in
// 'operations', if possible. If 'operations' is empty, then the
// master will send the latest status for each operation currently
// known.
type Call_ReconcileOperations struct {
	Operations           []*Call_ReconcileOperations_Operation `protobuf:"bytes,1,rep,name=operations" json:"operations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *Call_ReconcileOperations) Reset()         { *m = Call_ReconcileOperations{} }
func (m *Call_ReconcileOperations) String() string { return proto.CompactTextString(m) }
func (*Call_ReconcileOperations) ProtoMessage()    {}
func (*Call_ReconcileOperations) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{2, 11}
}

func (m *Call_ReconcileOperations) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call_ReconcileOperations.Unmarshal(m, b)
}
func (m *Call_ReconcileOperations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call_ReconcileOperations.Marshal(b, m, deterministic)
}
func (m *Call_ReconcileOperations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call_ReconcileOperations.Merge(m, src)
}
func (m *Call_ReconcileOperations) XXX_Size() int {
	return xxx_messageInfo_Call_ReconcileOperations.Size(m)
}
func (m *Call_ReconcileOperations) XXX_DiscardUnknown() {
	xxx_messageInfo_Call_ReconcileOperations.DiscardUnknown(m)
}

var xxx_messageInfo_Call_ReconcileOperations proto.InternalMessageInfo

func (m *Call_ReconcileOperations) GetOperations() []*Call_ReconcileOperations_Operation {
	if m != nil {
		return m.Operations
	}
	return nil
}

type Call_ReconcileOperations_Operation struct {
	OperationId *OperationID `protobuf:"bytes,1,req,name=operation_id,json=operationId" json:"operation_id,omitempty"`
	// If `agent_id` is not set and the master doesn't know the operation,
	// then it will return `OPERATION_UNKNOWN`; if `agent_id` is set, it can
	// return more fine-grained states depending on the state of the
	// corresponding agent.
	AgentId              *AgentID            `protobuf:"bytes,2,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	ResourceProviderId   *ResourceProviderID `protobuf:"bytes,3,opt,name=resource_provider_id,json=resourceProviderId" json:"resource_provider_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Call_ReconcileOperations_Operation) Reset()         { *m = Call_ReconcileOperations_Operation{} }
func (m *Call_ReconcileOperations_Operation) String() string { return proto.CompactTextString(m) }
func (*Call_ReconcileOperations_Operation) ProtoMessage()    {}
func (*Call_ReconcileOperations_Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{2, 11, 0}
}

func (m *Call_ReconcileOperations_Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call_ReconcileOperations_Operation.Unmarshal(m, b)
}
func (m *Call_ReconcileOperations_Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call_ReconcileOperations_Operation.Marshal(b, m, deterministic)
}
func (m *Call_ReconcileOperations_Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call_ReconcileOperations_Operation.Merge(m, src)
}
func (m *Call_ReconcileOperations_Operation) XXX_Size() int {
	return xxx_messageInfo_Call_ReconcileOperations_Operation.Size(m)
}
func (m *Call_ReconcileOperations_Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Call_ReconcileOperations_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Call_ReconcileOperations_Operation proto.InternalMessageInfo

func (m *Call_ReconcileOperations_Operation) GetOperationId() *OperationID {
	if m != nil {
		return m.OperationId
	}
	return nil
}

func (m *Call_ReconcileOperations_Operation) GetAgentId() *AgentID {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *Call_ReconcileOperations_Operation) GetResourceProviderId() *ResourceProviderID {
	if m != nil {
		return m.ResourceProviderId
	}
	return nil
}

// Sends arbitrary binary data to the executor. Note that Mesos
// neither interprets this data nor makes any guarantees about the
// delivery of this message to the executor.
type Call_Message struct {
	AgentId              *AgentID    `protobuf:"bytes,1,req,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	ExecutorId           *ExecutorID `protobuf:"bytes,2,req,name=executor_id,json=executorId" json:"executor_id,omitempty"`
	Data                 []byte      `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Call_Message) Reset()         { *m = Call_Message{} }
func (m *Call_Message) String() string { return proto.CompactTextString(m) }
func (*Call_Message) ProtoMessage()    {}
func (*Call_Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{2, 12}
}

func (m *Call_Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call_Message.Unmarshal(m, b)
}
func (m *Call_Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call_Message.Marshal(b, m, deterministic)
}
func (m *Call_Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call_Message.Merge(m, src)
}
func (m *Call_Message) XXX_Size() int {
	return xxx_messageInfo_Call_Message.Size(m)
}
func (m *Call_Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Call_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Call_Message proto.InternalMessageInfo

func (m *Call_Message) GetAgentId() *AgentID {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *Call_Message) GetExecutorId() *ExecutorID {
	if m != nil {
		return m.ExecutorId
	}
	return nil
}

func (m *Call_Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// Requests a specific set of resources from Mesos's allocator. If
// the allocator has support for this, corresponding offers will be
// sent asynchronously via the OFFERS event(s).
//
// NOTE: The built-in hierarchical allocator doesn't have support
// for this call and hence simply ignores it.
type Call_Request struct {
	Requests             []*Request `protobuf:"bytes,1,rep,name=requests" json:"requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Call_Request) Reset()         { *m = Call_Request{} }
func (m *Call_Request) String() string { return proto.CompactTextString(m) }
func (*Call_Request) ProtoMessage()    {}
func (*Call_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{2, 13}
}

func (m *Call_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call_Request.Unmarshal(m, b)
}
func (m *Call_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call_Request.Marshal(b, m, deterministic)
}
func (m *Call_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call_Request.Merge(m, src)
}
func (m *Call_Request) XXX_Size() int {
	return xxx_messageInfo_Call_Request.Size(m)
}
func (m *Call_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Call_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Call_Request proto.InternalMessageInfo

func (m *Call_Request) GetRequests() []*Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

// Suppress offers for the specified roles. If `roles` is empty,
// the `SUPPRESS` call will suppress offers for all of the roles
// the framework is currently subscribed to.
type Call_Suppress struct {
	Roles                []string `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Call_Suppress) Reset()         { *m = Call_Suppress{} }
func (m *Call_Suppress) String() string { return proto.CompactTextString(m) }
func (*Call_Suppress) ProtoMessage()    {}
func (*Call_Suppress) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{2, 14}
}

func (m *Call_Suppress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call_Suppress.Unmarshal(m, b)
}
func (m *Call_Suppress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call_Suppress.Marshal(b, m, deterministic)
}
func (m *Call_Suppress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call_Suppress.Merge(m, src)
}
func (m *Call_Suppress) XXX_Size() int {
	return xxx_messageInfo_Call_Suppress.Size(m)
}
func (m *Call_Suppress) XXX_DiscardUnknown() {
	xxx_messageInfo_Call_Suppress.DiscardUnknown(m)
}

var xxx_messageInfo_Call_Suppress proto.InternalMessageInfo

func (m *Call_Suppress) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

//*
// EXPERIMENTAL.
//
// This message is used by the C++ Scheduler HTTP API library as the return
// type of the `call()` method. The message includes the HTTP status code with
// which the master responded, and optionally a `scheduler::Response` message.
//
// There are three cases to consider depending on the HTTP response status code:
//
//  (1) '202 ACCEPTED': Indicates the call was accepted for processing and
//        neither `response` nor `error` will be set.
//
//  (2) '200 OK': Indicates the call completed successfully, and the `response`
//        field will be set if the `scheduler::Call::Type` has a corresponding
//        `scheduler::Response::Type`; `error` will not be set.
//
//  (3) For all other HTTP status codes, the `response` field will not be set
//      and the `error` field may be set to provide more information.
//
// NOTE: This message is used by the C++ Scheduler HTTP API library and is not
// part of the API specification.
type APIResult struct {
	// HTTP status code with which the master responded.
	StatusCode *uint32 `protobuf:"varint,1,req,name=status_code,json=statusCode" json:"status_code,omitempty"`
	// NOTE: After resolution of MESOS-9648, this field is not currently used by
	// Mesos. It is left in place in anticipation of future use.
	//
	// This field will only be set if the call completed successfully and the
	// master responded with `200 OK` and a non-empty body.
	Response *Response `protobuf:"bytes,2,opt,name=response" json:"response,omitempty"`
	// This field will only be set if the call did not complete successfully and
	// the master responded with a status other than `202 Accepted` or `200 OK`,
	// and with a non-empty body.
	Error                *string  `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIResult) Reset()         { *m = APIResult{} }
func (m *APIResult) String() string { return proto.CompactTextString(m) }
func (*APIResult) ProtoMessage()    {}
func (*APIResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{3}
}

func (m *APIResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIResult.Unmarshal(m, b)
}
func (m *APIResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIResult.Marshal(b, m, deterministic)
}
func (m *APIResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIResult.Merge(m, src)
}
func (m *APIResult) XXX_Size() int {
	return xxx_messageInfo_APIResult.Size(m)
}
func (m *APIResult) XXX_DiscardUnknown() {
	xxx_messageInfo_APIResult.DiscardUnknown(m)
}

var xxx_messageInfo_APIResult proto.InternalMessageInfo

func (m *APIResult) GetStatusCode() uint32 {
	if m != nil && m.StatusCode != nil {
		return *m.StatusCode
	}
	return 0
}

func (m *APIResult) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *APIResult) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func init() {
	proto.RegisterEnum("mesos.v1.Event_Type", Event_Type_name, Event_Type_value)
	proto.RegisterEnum("mesos.v1.Response_Type", Response_Type_name, Response_Type_value)
	proto.RegisterEnum("mesos.v1.Call_Type", Call_Type_name, Call_Type_value)
	proto.RegisterType((*Event)(nil), "mesos.v1.Event")
	proto.RegisterType((*Event_Subscribed)(nil), "mesos.v1.Event.Subscribed")
	proto.RegisterType((*Event_Offers)(nil), "mesos.v1.Event.Offers")
	proto.RegisterType((*Event_InverseOffers)(nil), "mesos.v1.Event.InverseOffers")
	proto.RegisterType((*Event_Rescind)(nil), "mesos.v1.Event.Rescind")
	proto.RegisterType((*Event_RescindInverseOffer)(nil), "mesos.v1.Event.RescindInverseOffer")
	proto.RegisterType((*Event_Update)(nil), "mesos.v1.Event.Update")
	proto.RegisterType((*Event_UpdateOperationStatus)(nil), "mesos.v1.Event.UpdateOperationStatus")
	proto.RegisterType((*Event_Message)(nil), "mesos.v1.Event.Message")
	proto.RegisterType((*Event_Failure)(nil), "mesos.v1.Event.Failure")
	proto.RegisterType((*Event_Error)(nil), "mesos.v1.Event.Error")
	proto.RegisterType((*Response)(nil), "mesos.v1.Response")
	proto.RegisterType((*Response_ReconcileOperations)(nil), "mesos.v1.Response.ReconcileOperations")
	proto.RegisterType((*Call)(nil), "mesos.v1.Call")
	proto.RegisterType((*Call_Subscribe)(nil), "mesos.v1.Call.Subscribe")
	proto.RegisterType((*Call_Accept)(nil), "mesos.v1.Call.Accept")
	proto.RegisterType((*Call_Decline)(nil), "mesos.v1.Call.Decline")
	proto.RegisterType((*Call_AcceptInverseOffers)(nil), "mesos.v1.Call.AcceptInverseOffers")
	proto.RegisterType((*Call_DeclineInverseOffers)(nil), "mesos.v1.Call.DeclineInverseOffers")
	proto.RegisterType((*Call_Revive)(nil), "mesos.v1.Call.Revive")
	proto.RegisterType((*Call_Kill)(nil), "mesos.v1.Call.Kill")
	proto.RegisterType((*Call_Shutdown)(nil), "mesos.v1.Call.Shutdown")
	proto.RegisterType((*Call_Acknowledge)(nil), "mesos.v1.Call.Acknowledge")
	proto.RegisterType((*Call_AcknowledgeOperationStatus)(nil), "mesos.v1.Call.AcknowledgeOperationStatus")
	proto.RegisterType((*Call_Reconcile)(nil), "mesos.v1.Call.Reconcile")
	proto.RegisterType((*Call_Reconcile_Task)(nil), "mesos.v1.Call.Reconcile.Task")
	proto.RegisterType((*Call_ReconcileOperations)(nil), "mesos.v1.Call.ReconcileOperations")
	proto.RegisterType((*Call_ReconcileOperations_Operation)(nil), "mesos.v1.Call.ReconcileOperations.Operation")
	proto.RegisterType((*Call_Message)(nil), "mesos.v1.Call.Message")
	proto.RegisterType((*Call_Request)(nil), "mesos.v1.Call.Request")
	proto.RegisterType((*Call_Suppress)(nil), "mesos.v1.Call.Suppress")
	proto.RegisterType((*APIResult)(nil), "mesos.v1.APIResult")
}

func init() { proto.RegisterFile("scheduler.proto", fileDescriptor_2b3fc28395a6d9c5) }

var fileDescriptor_2b3fc28395a6d9c5 = []byte{
	// 1808 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0xcf, 0x73, 0xdb, 0x4e,
	0x15, 0x47, 0x8e, 0x7f, 0x3e, 0xc7, 0x8e, 0xb2, 0x89, 0x13, 0x55, 0xa4, 0x10, 0xcc, 0xc0, 0x37,
	0x9d, 0x6f, 0xeb, 0x69, 0xda, 0xa1, 0x14, 0x68, 0x99, 0x71, 0x6c, 0xa5, 0x15, 0x4d, 0x6d, 0xb3,
	0xb2, 0xd3, 0x81, 0x99, 0x8e, 0x46, 0xb5, 0xd6, 0x89, 0x26, 0x8a, 0x65, 0x24, 0xd9, 0xa5, 0xdc,
	0xe8, 0x81, 0x23, 0x47, 0xce, 0x70, 0x83, 0x0b, 0xff, 0x00, 0x47, 0x2e, 0xfc, 0x17, 0x5c, 0xf9,
	0x33, 0x98, 0x5d, 0xad, 0x64, 0x49, 0x96, 0x9b, 0x84, 0x19, 0x18, 0x6e, 0xd2, 0xbe, 0xcf, 0x7b,
	0xfb, 0xfc, 0xf4, 0xd9, 0xcf, 0xbe, 0x67, 0xd8, 0xf2, 0xc6, 0x97, 0xc4, 0x9c, 0xdb, 0xc4, 0x6d,
	0xcd, 0x5c, 0xc7, 0x77, 0x50, 0xf9, 0x9a, 0x78, 0x8e, 0xd7, 0x5a, 0x1c, 0xcb, 0xd5, 0xe0, 0x89,
	0x2d, 0x37, 0xff, 0x59, 0x83, 0x82, 0xb2, 0x20, 0x53, 0x1f, 0x1d, 0x41, 0xde, 0xff, 0x34, 0x23,
	0x92, 0x70, 0x28, 0x1c, 0xd5, 0x9f, 0xec, 0xb6, 0x42, 0x7c, 0x8b, 0x99, 0x5b, 0xc3, 0x4f, 0x33,
	0x82, 0x19, 0x02, 0xfd, 0x18, 0xc0, 0x9b, 0x7f, 0xf0, 0xc6, 0xae, 0xf5, 0x81, 0x98, 0x52, 0xee,
	0x50, 0x38, 0xaa, 0x3e, 0x91, 0xd3, 0x78, 0x2d, 0x42, 0xe0, 0x18, 0x1a, 0xb5, 0xa0, 0xe8, 0x4c,
	0x26, 0xc4, 0xf5, 0xa4, 0x0d, 0xe6, 0xb7, 0x97, 0xf6, 0xeb, 0x33, 0x2b, 0xe6, 0x28, 0xd4, 0x85,
	0xba, 0x35, 0x5d, 0x10, 0xd7, 0x23, 0x3a, 0xf7, 0xab, 0x30, 0xbf, 0xfb, 0x69, 0x3f, 0x35, 0x40,
	0x71, 0xf7, 0x9a, 0x15, 0x7f, 0x45, 0xc7, 0x50, 0x72, 0x89, 0x37, 0xb6, 0xa6, 0xa6, 0x94, 0x67,
	0xee, 0xfb, 0x69, 0x77, 0x1c, 0x98, 0x71, 0x88, 0x43, 0xef, 0xa0, 0xc1, 0x1f, 0xf5, 0x44, 0x02,
	0x12, 0xb0, 0x00, 0xdf, 0x5d, 0x13, 0x20, 0x9e, 0x06, 0xde, 0x71, 0x57, 0x17, 0x69, 0x05, 0xe6,
	0x33, 0xd3, 0xf0, 0x89, 0x54, 0xc8, 0xae, 0xc0, 0x88, 0x59, 0x31, 0x47, 0xa1, 0xf7, 0xb0, 0x1f,
	0x3c, 0xe9, 0xce, 0x8c, 0xb8, 0x86, 0x6f, 0x39, 0x53, 0xdd, 0xf3, 0x0d, 0x7f, 0xee, 0x49, 0x55,
	0x16, 0xe0, 0x7b, 0xd9, 0x01, 0xfa, 0x21, 0x5a, 0x63, 0x60, 0xdc, 0x98, 0x67, 0x2d, 0xd3, 0xd2,
	0x5c, 0x13, 0xcf, 0x33, 0x2e, 0x88, 0x54, 0xcc, 0x2e, 0xcd, 0xdb, 0xc0, 0x8c, 0x43, 0x1c, 0x75,
	0x99, 0x18, 0x96, 0x3d, 0x77, 0x89, 0x54, 0xca, 0x76, 0x39, 0x0d, 0xcc, 0x38, 0xc4, 0xa1, 0xaf,
	0xa1, 0x40, 0x5c, 0xd7, 0x71, 0xa5, 0x32, 0x73, 0x68, 0xa4, 0x1d, 0x14, 0x6a, 0xc4, 0x01, 0x46,
	0xfe, 0x9b, 0x00, 0xb0, 0xa4, 0x0f, 0x7a, 0x0e, 0x9b, 0x13, 0xd7, 0xb8, 0x26, 0x1f, 0x1d, 0xf7,
	0x4a, 0xb7, 0x4c, 0x49, 0x38, 0xcc, 0x25, 0x43, 0x9c, 0x86, 0x56, 0xb5, 0x8b, 0xab, 0x11, 0x54,
	0x35, 0xd1, 0x0b, 0x90, 0x2f, 0x89, 0xe1, 0xfa, 0x1f, 0x88, 0xe1, 0xeb, 0xd6, 0xd4, 0x27, 0xee,
	0xc2, 0xb0, 0x75, 0x8f, 0x8c, 0x9d, 0xa9, 0xe9, 0x31, 0xe2, 0x0a, 0x58, 0x8a, 0x10, 0x2a, 0x07,
	0x68, 0x81, 0x1d, 0xfd, 0x00, 0xaa, 0xd7, 0x86, 0xe7, 0x13, 0x57, 0xb7, 0xa6, 0x13, 0x87, 0xf3,
	0x35, 0x76, 0x2e, 0xde, 0x32, 0xa3, 0x3a, 0x9d, 0x38, 0x18, 0xae, 0xa3, 0x67, 0xf9, 0x18, 0x8a,
	0x9c, 0x75, 0x5f, 0x45, 0x5c, 0x17, 0x0e, 0x37, 0x8e, 0xaa, 0x4f, 0xb6, 0x96, 0xbe, 0x01, 0x3f,
	0xb8, 0x59, 0xee, 0x41, 0x2d, 0x41, 0x5f, 0xf4, 0x72, 0x85, 0xf5, 0x41, 0x84, 0x18, 0x57, 0x12,
	0x44, 0x4b, 0xd2, 0x5d, 0xfe, 0x21, 0x94, 0x38, 0x1d, 0xd1, 0x43, 0x28, 0xb3, 0x08, 0xcb, 0xc2,
	0x6d, 0xa7, 0xb2, 0x50, 0xbb, 0xb8, 0xc4, 0x20, 0xaa, 0x29, 0x63, 0xd8, 0xc9, 0xe0, 0x31, 0xfa,
	0x09, 0x88, 0x89, 0x74, 0xbe, 0x18, 0xac, 0x1e, 0xcf, 0x45, 0x35, 0xe5, 0x67, 0x50, 0x0c, 0x08,
	0x89, 0x1e, 0x42, 0x91, 0x13, 0x37, 0x70, 0x8e, 0xd5, 0x72, 0x68, 0x78, 0x57, 0x9c, 0xa7, 0x1c,
	0x23, 0xff, 0x0c, 0x1a, 0xa3, 0x35, 0x8c, 0x4d, 0x86, 0xb9, 0x17, 0xcb, 0x21, 0xc5, 0xf9, 0x30,
	0xd6, 0x67, 0x01, 0x4a, 0x9c, 0xc6, 0xb4, 0x22, 0xc6, 0x05, 0x99, 0xfa, 0x99, 0x3f, 0xa2, 0x4d,
	0x2d, 0xb4, 0x22, 0x0c, 0xa2, 0x9a, 0x94, 0x04, 0xe4, 0xd7, 0x64, 0x3c, 0xf7, 0x1d, 0xf6, 0xab,
	0x73, 0xe9, 0xc4, 0x15, 0x6e, 0x54, 0xbb, 0x18, 0x42, 0xa0, 0x6a, 0x22, 0x04, 0x79, 0xd3, 0xf0,
	0x0d, 0x69, 0xe3, 0x30, 0x77, 0xb4, 0x89, 0xd9, 0xb3, 0xfc, 0x3b, 0x01, 0x4a, 0xfc, 0x60, 0xa4,
	0x92, 0x10, 0xee, 0x9a, 0x84, 0x70, 0xab, 0x24, 0xf6, 0xa2, 0x42, 0x51, 0xee, 0x16, 0xa2, 0x6a,
	0x7c, 0x07, 0x0a, 0xec, 0xbc, 0x21, 0x69, 0x79, 0xf6, 0x69, 0x25, 0x2a, 0xd1, 0x11, 0x6f, 0xfe,
	0x43, 0x80, 0x3c, 0x55, 0x7c, 0x54, 0x85, 0xd2, 0xa8, 0xf7, 0xa6, 0xd7, 0x7f, 0xd7, 0x13, 0xbf,
	0x81, 0xea, 0x00, 0xda, 0xe8, 0x44, 0xeb, 0x60, 0xf5, 0x44, 0xe9, 0x8a, 0x02, 0x02, 0x28, 0xf6,
	0x4f, 0x4f, 0x15, 0xac, 0x89, 0x39, 0x84, 0xa0, 0xae, 0xf6, 0xce, 0x15, 0xac, 0x29, 0x3a, 0x5f,
	0xab, 0x50, 0x67, 0xac, 0x68, 0x1d, 0xb5, 0xd7, 0x15, 0x37, 0xd0, 0x3d, 0x68, 0xf0, 0x17, 0x3d,
	0x01, 0x14, 0x81, 0xc6, 0x19, 0x0d, 0xba, 0xed, 0xa1, 0x22, 0xe6, 0xd1, 0x37, 0x61, 0x3f, 0x78,
	0xd6, 0xfb, 0x03, 0x05, 0xb7, 0x87, 0x6a, 0xbf, 0xa7, 0x6b, 0xc3, 0xf6, 0x70, 0xa4, 0x89, 0x55,
	0x1a, 0xf0, 0xad, 0xa2, 0x69, 0xed, 0x57, 0x8a, 0x58, 0xa0, 0x2f, 0xa7, 0x6d, 0xf5, 0x6c, 0x84,
	0x15, 0xb1, 0x88, 0x2a, 0x50, 0x50, 0x30, 0xee, 0x63, 0xb1, 0x84, 0x6a, 0x50, 0x79, 0xad, 0xb4,
	0xf1, 0xf0, 0x44, 0x69, 0x0f, 0xc5, 0x72, 0xf3, 0xaf, 0x39, 0x28, 0x63, 0xe2, 0xcd, 0x9c, 0xa9,
	0x47, 0x75, 0x28, 0x7e, 0xc9, 0xc5, 0x74, 0x2b, 0x44, 0xc4, 0xef, 0xb9, 0xf7, 0xb0, 0xeb, 0x52,
	0x2d, 0x18, 0x5b, 0x76, 0x4c, 0x7c, 0x3d, 0x5e, 0xff, 0xef, 0x67, 0x38, 0xe3, 0x10, 0x1e, 0x11,
	0xd1, 0x3b, 0xc9, 0x49, 0x02, 0xbd, 0x08, 0x56, 0x0c, 0xf2, 0x98, 0x1e, 0xb6, 0x95, 0x65, 0x74,
	0x06, 0x28, 0x2d, 0xf4, 0x24, 0x3c, 0xff, 0xeb, 0xa9, 0xce, 0xb6, 0xd9, 0x76, 0x92, 0x8b, 0xc4,
	0x6b, 0x1e, 0x67, 0x7d, 0xc7, 0x03, 0xd8, 0xc5, 0x4a, 0xa7, 0xdf, 0xeb, 0xa8, 0x67, 0xb1, 0x32,
	0x6b, 0xa2, 0x20, 0xe7, 0xca, 0x42, 0xf3, 0xf7, 0x32, 0xe4, 0x3b, 0x86, 0x6d, 0x67, 0x08, 0xaf,
	0x70, 0x4b, 0xe1, 0xfd, 0x8a, 0x97, 0x39, 0xc7, 0xca, 0xbc, 0xb3, 0xf4, 0xa0, 0x71, 0xe3, 0x25,
	0x7e, 0x06, 0x95, 0xa8, 0x39, 0xe0, 0x0a, 0x2b, 0xa5, 0xd0, 0xd1, 0x4d, 0x80, 0x97, 0x50, 0xf4,
	0x08, 0x8a, 0xc6, 0x78, 0x4c, 0x66, 0x3e, 0xbf, 0xcf, 0x1b, 0x29, 0xa7, 0x36, 0x33, 0x62, 0x0e,
	0x42, 0x8f, 0xa1, 0x64, 0x92, 0xb1, 0x6d, 0x4d, 0x33, 0x2e, 0x5d, 0x86, 0xef, 0x06, 0x56, 0x1c,
	0xc2, 0xd0, 0x39, 0x34, 0x02, 0x5f, 0x3d, 0x25, 0xc4, 0x35, 0xe6, 0xdf, 0xcc, 0xdc, 0x2f, 0xd9,
	0x83, 0xec, 0x18, 0xab, 0x8b, 0xe8, 0x17, 0xb0, 0xc7, 0xb7, 0x48, 0x07, 0xae, 0xa7, 0xfb, 0x8a,
	0x78, 0x62, 0xc9, 0xc8, 0xbb, 0x66, 0xc6, 0x2a, 0xad, 0x89, 0x4b, 0x16, 0xd6, 0x82, 0x48, 0x5b,
	0x99, 0x35, 0xc1, 0xcc, 0x88, 0x39, 0x88, 0x7e, 0xa3, 0x2b, 0xcb, 0xb6, 0xf9, 0xad, 0x9f, 0xfe,
	0x46, 0x6f, 0x2c, 0xdb, 0xc6, 0x0c, 0x80, 0x9e, 0x42, 0xd9, 0xbb, 0x9c, 0xfb, 0xa6, 0xf3, 0x71,
	0xba, 0x7a, 0xdf, 0x07, 0x9f, 0x88, 0x9b, 0x71, 0x04, 0x44, 0x2f, 0xa0, 0x6a, 0x8c, 0xaf, 0xa6,
	0xce, 0x47, 0x9b, 0x98, 0x17, 0x84, 0x5f, 0xfb, 0xf2, 0x4a, 0xd5, 0x22, 0x04, 0x8e, 0xc3, 0xd1,
	0x15, 0x1c, 0xc4, 0x5e, 0x57, 0x1b, 0x9f, 0x6d, 0x16, 0xee, 0xc1, 0xfa, 0x70, 0xe9, 0x8b, 0x40,
	0x36, 0xd6, 0xda, 0x28, 0x07, 0xa3, 0xe3, 0xc9, 0xbb, 0x4b, 0x69, 0xa5, 0x74, 0xdc, 0x8e, 0x97,
	0x50, 0x34, 0x5a, 0x23, 0x0f, 0x28, 0x93, 0x21, 0x19, 0x47, 0x3d, 0x53, 0x16, 0x28, 0x57, 0x43,
	0x51, 0x86, 0x4c, 0xae, 0xae, 0xf4, 0x63, 0x8f, 0x69, 0x77, 0xfb, 0xab, 0x39, 0xf1, 0x7c, 0xde,
	0x11, 0xee, 0xad, 0xec, 0xcd, 0xac, 0x38, 0x84, 0xb1, 0x4f, 0x3a, 0x9f, 0xcd, 0x5c, 0xe2, 0x79,
	0x92, 0x98, 0xfd, 0x49, 0xb9, 0x19, 0x47, 0x40, 0x79, 0x01, 0x95, 0xe8, 0x2c, 0xa2, 0x9f, 0x42,
	0x3d, 0xa6, 0x0d, 0xb4, 0x3f, 0x0a, 0xee, 0xd2, 0xfd, 0x2c, 0x75, 0xa0, 0x2d, 0x52, 0x6d, 0x12,
	0x7f, 0x45, 0x0f, 0x40, 0x0c, 0x03, 0x13, 0x53, 0x77, 0x1d, 0x9b, 0x50, 0x5d, 0xdd, 0x38, 0xaa,
	0xe0, 0xad, 0xe5, 0x3a, 0xa6, 0xcb, 0xf2, 0x1f, 0x05, 0x28, 0x06, 0xe7, 0x0b, 0xb5, 0xa0, 0x12,
	0x36, 0x20, 0xa1, 0x24, 0x66, 0x74, 0x20, 0x65, 0xde, 0xce, 0x78, 0xe8, 0x47, 0x00, 0x09, 0xdd,
	0x4e, 0x6b, 0x28, 0xc5, 0x2d, 0x95, 0x14, 0xc7, 0xc0, 0xe8, 0x6b, 0x28, 0x4d, 0x2c, 0xdb, 0x5f,
	0x4e, 0x2a, 0xb1, 0x8d, 0x4e, 0x03, 0x03, 0x0e, 0x11, 0xf2, 0x04, 0x4a, 0xfc, 0xa0, 0xde, 0x39,
	0xc5, 0xd8, 0x3e, 0xb9, 0x1b, 0xf7, 0xf9, 0xad, 0x00, 0x3b, 0x19, 0x52, 0x83, 0x5e, 0xc2, 0x76,
	0xba, 0x41, 0xfb, 0xc2, 0xe6, 0x5b, 0xc9, 0x0e, 0xed, 0x8e, 0x39, 0x7c, 0x16, 0x60, 0x37, 0x4b,
	0x95, 0xfe, 0xa7, 0x49, 0x7c, 0x0b, 0x8a, 0x81, 0x9c, 0xa1, 0x5d, 0x28, 0x04, 0xec, 0x11, 0x18,
	0x7b, 0x82, 0x17, 0xf9, 0x0f, 0x02, 0xe4, 0xa9, 0x84, 0xa1, 0x07, 0x50, 0xf2, 0x0d, 0x2f, 0x36,
	0x37, 0x88, 0xc9, 0xa6, 0x53, 0xed, 0xe2, 0x22, 0x05, 0xa8, 0x66, 0xa2, 0x27, 0xcb, 0xdd, 0xa6,
	0x27, 0xa3, 0xea, 0xa8, 0xcf, 0x1c, 0xdb, 0x1a, 0x7f, 0x5a, 0x9d, 0x0e, 0xe8, 0xee, 0x03, 0x66,
	0xc3, 0x70, 0x15, 0x3d, 0xcb, 0x0e, 0x94, 0x43, 0xb5, 0x4c, 0xb7, 0x75, 0xc2, 0x2d, 0x7b, 0xcb,
	0x64, 0x9e, 0x37, 0x34, 0xb0, 0xf2, 0x6f, 0xa0, 0x1a, 0xd3, 0xc5, 0x3b, 0x76, 0xbf, 0xb1, 0xea,
	0xe5, 0x6e, 0xa8, 0x1e, 0x82, 0xfc, 0x7c, 0x6e, 0x99, 0x61, 0xc7, 0x4b, 0x9f, 0xe5, 0x7f, 0x09,
	0x20, 0xaf, 0x17, 0xe5, 0x3b, 0x36, 0xc1, 0x3d, 0x2a, 0xb7, 0x9e, 0x33, 0x77, 0xc7, 0x44, 0x9f,
	0xb9, 0xce, 0xc2, 0x32, 0x49, 0xac, 0x1b, 0x3e, 0x48, 0x74, 0x63, 0x0c, 0x35, 0xe0, 0x20, 0xb5,
	0x8b, 0x91, 0x9b, 0x5e, 0xcb, 0x4c, 0x98, 0x76, 0x3c, 0xcb, 0xbb, 0xc6, 0x32, 0xa5, 0x7c, 0x7a,
	0xd4, 0x8c, 0x7e, 0x02, 0xed, 0x78, 0x22, 0xa8, 0x6a, 0xca, 0x7f, 0x12, 0xa0, 0x12, 0x49, 0x3c,
	0x7a, 0x0a, 0x05, 0x5a, 0x96, 0x90, 0xfe, 0xf7, 0xd7, 0xdd, 0x05, 0xac, 0x88, 0x38, 0xc0, 0xca,
	0x3a, 0xe4, 0xe9, 0xeb, 0x7f, 0x8d, 0xb2, 0xf2, 0x5f, 0x72, 0xeb, 0x3a, 0xce, 0xb8, 0x4a, 0x06,
	0x29, 0x3f, 0xbc, 0xf9, 0xfa, 0xca, 0x16, 0x4e, 0xf9, 0xef, 0x02, 0x54, 0x22, 0xcb, 0x4a, 0x45,
	0x85, 0xdb, 0x56, 0xf4, 0x8e, 0xc7, 0x71, 0x1d, 0x3b, 0x36, 0xfe, 0x33, 0x76, 0xfc, 0x7f, 0x4c,
	0x8c, 0xcf, 0xe9, 0x1c, 0x1f, 0xdc, 0xd8, 0x8f, 0xa0, 0xcc, 0x2f, 0xef, 0x0c, 0x4d, 0x0d, 0xef,
	0xf7, 0x08, 0x22, 0x1f, 0x42, 0x39, 0xbc, 0xc1, 0xb3, 0x15, 0xb2, 0xf9, 0xe7, 0x5c, 0xd6, 0x64,
	0x50, 0x83, 0x4a, 0x34, 0xe1, 0x89, 0x02, 0xda, 0x84, 0xf2, 0x50, 0x69, 0xe3, 0x2e, 0x35, 0xe6,
	0xe8, 0x98, 0xd6, 0xee, 0x74, 0x94, 0xc1, 0x50, 0xdc, 0xa0, 0x5e, 0x5d, 0xa5, 0x73, 0xa6, 0xf6,
	0xe8, 0xcc, 0x76, 0x0f, 0x1a, 0x81, 0x41, 0x4f, 0x8d, 0x80, 0x35, 0x24, 0xc3, 0x1e, 0xc7, 0xa5,
	0x6d, 0x75, 0x1a, 0x0f, 0x2b, 0xe7, 0xea, 0x39, 0x1d, 0xe6, 0xca, 0x90, 0x7f, 0xa3, 0x9e, 0x9d,
	0x89, 0x45, 0xba, 0xa7, 0xf6, 0x7a, 0x34, 0x64, 0x7b, 0x96, 0xd0, 0x16, 0x54, 0xdb, 0x1d, 0x9a,
	0xdd, 0x99, 0xd2, 0x7d, 0xa5, 0x88, 0x65, 0x74, 0x08, 0x07, 0xb1, 0x85, 0xd5, 0x21, 0x71, 0x8b,
	0xfe, 0x86, 0x68, 0xba, 0x11, 0x2b, 0x48, 0x5a, 0x33, 0xec, 0x88, 0xf1, 0x69, 0x12, 0x82, 0x59,
	0xf5, 0xe7, 0x23, 0x45, 0x1b, 0x8a, 0x55, 0x96, 0xc3, 0x68, 0x30, 0xc0, 0x8a, 0xa6, 0x89, 0x9b,
	0x4d, 0x17, 0x2a, 0xed, 0x81, 0x8a, 0x89, 0x37, 0xb7, 0x7d, 0xf4, 0x6d, 0xa8, 0x06, 0x4d, 0xa8,
	0x3e, 0x76, 0xcc, 0x60, 0x6e, 0xae, 0x61, 0x08, 0x96, 0x3a, 0x8e, 0x49, 0x1b, 0x80, 0xb2, 0xcb,
	0xe7, 0x41, 0xce, 0x5b, 0xb4, 0x3a, 0x29, 0xe2, 0x08, 0x43, 0x3f, 0x4f, 0xf0, 0xd7, 0x18, 0xa5,
	0x6a, 0x85, 0xff, 0x07, 0x76, 0xf2, 0x14, 0xee, 0x3b, 0xee, 0x45, 0xcb, 0x98, 0x19, 0xe3, 0x4b,
	0xb2, 0xf4, 0x8f, 0xfe, 0xd5, 0x3d, 0x29, 0x0e, 0x5c, 0xc7, 0x77, 0xbc, 0x5f, 0x02, 0xb3, 0xb1,
	0x3f, 0x73, 0xff, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xed, 0x64, 0x0e, 0xf5, 0x15, 0x00, 0x00,
}
